# Arbitrary Goals and Artificial Rules

## Learning Objectives

- Understand the concept of arbitrary goals and artificial rules.
- Understand how arbitrary goals and artificial rules can be used to create engaging games.
- Understand how arbitrary goals and artificial rules can be used to create engaging art.

## Introduction

There is an ongoing debate about the seeming pointlessness of games. I've wrestled personally with this idea, namely that something so engaging, could be a waste of time. I've also fielded this complaint from students I've had. "This is all entertaining, but please tell me what I need to know to get the grade I want on the test that you are making me take". I've personally made additional goals for myself that would make my other desires seem less lofty. For instance, at one point towards the start of the pandemic, I made a proposal to my church to conduct a men's bible study in a virtual world. I suggested *Eve Online*, thinking that it would be a way to meet without having to unnecessarily risk contamination. I never heard anything back, and to be honest, I think my proposal was selfishly motivated. I wanted a way to play *Eve* and still tell myself that I was being productive. I am no longer suffering from such self-doubts, however it is still not clear to me whether or not I should be.

There are two lines of thought, namely that video games are a waste of time, or achieve no other real purpose than say popular entertainment. A part of the reason is the manufacture of artificial goals. However, these goals often enable alternate modes of being, for instance absorption which can give rise to other experiences like frustration, isolation, invention, or epiphany. For instance, I created my own goals by proposing the men's bible study. However, the real artificial goals at center of the ongoing debate are those goals derived by the game's developer. In order for a player to play a given game, they must adopt the goals given them by the game's developer. For instance in the game *Sign*, participants must be able to communicate a deep truth to one another using a completely arbitrary and made up language. Deviating from the rules set by the developer will prevent the player from being able to participate in that particular activity.

I wrestled with this idea for years afterward that our lives would become more imaginative, creative, with a majority of our time traversing between both virtual and physical worlds. Much later in life, the pandemic happened. Shortly before this however, I discovered a new genre of video games, namely space sims. These included games like *Elite Dangerous*, *Star Citizen*, and *Eve Online*. At first, I only had the computational ability to play *Eve Online* and *Elite Dangerous*. I was never particularly any good. In part this was because I was more interested in experiencing not only the visual effects, but the expansive way in which human relationships could be manipulated and enhanced. At one point in *Eve Online*, I was brave enough to venture into low sec. I lasted not even 3 minutes before another human being spawned at my location and obliterated my character. It was a significant setback and I remember very vividly the fear I felt, the disappointment concerning my decision to venture into low sec, my feeling of loss for having lost all of the items I had carried with me. Even now it is difficult for me to separate the feelings I had from those I would have experienced if I were standing on the side of a freeway watching as an out of control car was barrelling towards me. I felt helplessness and confusion, and all for a game.

Importantly, Nguyen argues that these alternative modes of being are only made possible when we commit ourselves to the game, by adopting its rules, ensuring that we pursue what would otherwise be an arbitrary goal. But, we might think that here we've found a way to mitigate the seeming pointlessness of the activity. The goal gives rise to the other experiences such as disappointment, fear, confusion, exhilaration etc.

My current game is Star Citizen. Star Citizen is a space sim currently under development by the company CIG. The developer's stated goals over all aren't clear, however they are incredibly ambitious. Star Citizen is a crowd funded endeavor and to date has raised close to 800 million dollars. The money earned has generally been through the sell of in-game items such as ships and armor. While players can use credits earned in the game for various ship and component purchases and the like, ships purchased through the pledge store come with lifetime warranties meaning the purchaser will always possess them regardless of how many times they are destroyed. This is important because the game's architect, Chris Roberts, has stated more than once that they intend to develop an in-game feature known as "Death of a Spaceman". The idea is that after so many deaths, the player's character will die and the player will have to develop a new character from scratch, earning all ships, components, armor and whatever else can be obtained through game-play.

Significant about this game, is the fact that it does a better job of giving the player to ability to more fully engage their agency in the context of the game. I currently belong to a large in-game organization. In this organization, we have many potential roles and responsibilities. There are two sets of roles, military and civilian. The military roles protect the civilian roles during various industry operations such as mining for mineral or ore, or salvaging ships that have been destroyed due to combat. The military roles also conduct operations in the game that aim to make the game "safe" for non-org members. Games like Star Citizen often have a number of what are called "Griefers". These are individuals have have a significant level of skill and often use that skill to make progress for less skilled players difficult or impossible. In part, it was these kinds of activities that caused significant headaches for the developer's of *Eve Online*. At one point is was practically impossible for newer players to become established enough to make the game interesting for them. Without new players, it was significantly impossible for *Eve* to experience continued growth. Our org has taken it upon themselves to organize collective game-play with the sole goal of protecting areas of lucrative activity from "Griefers" and other pirates. The org has given names to these roles and responsibilities like trading, mining, salvage, marines, navy, competition, engineering to name but a few. Additionally, one has to complete training for a given role in order to borrow money (aUEC) from the corp's bank to buy larger ships or weapons and other component upgrades.

Each of these, the roles, the rules for borrowing credits, "Death of a Spaceman", etc., may seem arbitrary on the surface. But more importantly, there is a significant distinction between the goals provided by the developer, and those developed by the player. Even more importantly here, the developer does not create rules, but rather creates environmental constraints such as centrifugal force that the player needs to learn to recognize and manipulate in order to develop her own rules, such as the proper salute, two ships fly to a distance of 6 kilometers as represented on their game's holo screen, face and fly towards each other turning the under belly of your ship to the other person when passing.

This is a prime example of the ways in which video games constitutes an aesthetic experience. It is an experience predicated upon the perceptions afforded to the player. The question that remains is what is the relationship between the player's newfound agency and the aesthetic experience? Could the aesthetic experience be had without the enhanced agency provided by the developer?
